export const WILAYAS = [
  "Adrar","Chlef","Laghouat","Oum El Bouaghi","Batna","Béjaïa","Biskra","Béchar","Blida","Bouira",
  "Tamanrasset","Tébessa","Tlemcen","Tiaret","Tizi Ouzou","Alger","Djelfa","Jijel","Sétif","Saïda",
  "Skikda","Sidi Bel Abbès","Annaba","Guelma","Constantine","Médéa","Mostaganem","M'Sila","Mascara","Ouargla",
  "Oran","El Bayadh","Illizi","Bordj Bou Arréridj","Boumerdès","El Tarf","Tindouf","Tissemsilt","El Oued","Khenchela",
  "Souk Ahras","Tipaza","Mila","Aïn Defla","Naâma","Aïn Témouchent","Ghardaïa","Relizane",
  "Timimoun","Bordj Badji Mokhtar","Ouled Djellal","Béni Abbès","In Salah","In Guezzam","Touggourt","Djanet","El M'Ghair","El Meniaa"
];

export const BRANDS = [
  "Abarth",
  "Acura",
  "Aion",
  "Aito",
  "Alfa Romeo",
  "Alpine",
  "Ariel",
  "Aston Martin",
  "Audi",
  "Avatr",
  "BAW",
  "BMW",
  "BYD",
  "Baic",
  "Bentley",
  "Bestune",
  "Borgward",
  "Brilliance",
  "Bristol",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Callaway",
  "Caterham",
  "Chana",
  "Changan",
  "Changhe",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Coda",
  "Cupra",
  "DFM",
  "DFSK",
  "DMC",
  "Dacia",
  "Dadi",
  "Daewoo",
  "Daihatsu",
  "De Tomaso",
  "Deepal",
  "Denza",
  "Dodge",
  "Dongfeng",
  "Eagle",
  "Exeed",
  "Fang Cheng Bao",
  "Faw",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Foton",
  "Fuqi",
  "GMC",
  "GWM Tank",
  "Gac",
  "Geely",
  "Geely Emgrand",
  "Geely Englon",
  "Geely Galaxy",
  "Geely Gleagle",
  "Genesis",
  "Gonow",
  "Great Wall",
  "Groz",
  "Hafei",
  "Haima",
  "Haval",
  "Hawtai",
  "Heibao",
  "HiPhi",
  "Hindustan",
  "Hispano-Suiza",
  "Honda",
  "Hongqi",
  "Hozon",
  "Huanghai",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "JAC",
  "JMC",
  "Jaecoo",
  "Jaguar",
  "Jeep",
  "Jetour",
  "Jetta",
  "Jonway",
  "Joylong",
  "KTM X-Bow",
  "Kaiyi",
  "Karma",
  "Karry",
  "Kia",
  "Koenigsegg",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Landwind",
  "Leapmotor",
  "Lexus",
  "Li Auto",
  "Lifan",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Luxeed",
  "Luxgen",
  "Lynk & Co",
  "MG",
  "Mahindra",
  "Maruti",
  "Maserati",
  "Maxus",
  "Maybach",
  "Mazda",
  "McLaren",
  "Melkus",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Neta",
  "Nio",
  "Nissan",
  "Oldsmobile",
  "Omoda",
  "Opel",
  "Ora",
  "Pagani",
  "Perodua",
  "Peugeot",
  "Pininfarina",
  "Plymouth",
  "Poer",
  "Polarsun",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Premier",
  "Proton",
  "Radar",
  "Ram",
  "Renault",
  "Rivian",
  "Roewe",
  "Rolls-Royce",
  "Rover",
  "Rover MG",
  "SRT",
  "SSC",
  "SWM",
  "Saab",
  "Saleen",
  "Saturn",
  "Scion",
  "Seat",
  "Seres",
  "Shineray",
  "Shuanghuan",
  "Skoda",
  "Smart",
  "Soueast",
  "Spyker",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tata",
  "Tesla",
  "Think",
  "Tianma",
  "Toyota",
  "Trabant",
  "Tramontana",
  "Trumpchi",
  "VGV",
  "Vauxhall",
  "Vector",
  "Venucia",
  "Volkswagen",
  "Volvo",
  "Voyah",
  "W Motors",
  "Wartburg",
  "Wey",
  "Wiesmann",
  "Wuling",
  "Xinkai",
  "Xpeng",
  "Yangwang",
  "Yema",
  "Youngman",
  "Zeekr",
  "Zhihud",
  "Zotye",
  "iCar",
];
