/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyAppointmentsRouteImport } from './routes/my-appointments'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PostRouteImport } from './routes/post'
import { Route as PostReelRouteImport } from './routes/post-reel'
import { Route as PostStoryRouteImport } from './routes/post-story'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as UnifiedInboxRouteImport } from './routes/unified-inbox'
import { Route as EditListingIdRouteImport } from './routes/edit-listing.$id'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppointmentsRoute = MyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PostReelRoute = PostReelRouteImport.update({
  id: '/post-reel',
  path: '/post-reel',
  getParentRoute: () => rootRouteImport,
} as any)
const PostStoryRoute = PostStoryRouteImport.update({
  id: '/post-story',
  path: '/post-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const UnifiedInboxRoute = UnifiedInboxRouteImport.update({
  id: '/unified-inbox',
  path: '/unified-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EditListingIdRoute = EditListingIdRouteImport.update({
  id: '/edit-listing/$id',
  path: '/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/messages': typeof MessagesRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/my-listings': typeof MyListingsRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/post-story': typeof PostStoryRoute
  '/reels': typeof ReelsRoute
  '/unified-inbox': typeof UnifiedInboxRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/messages': typeof MessagesRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/my-listings': typeof MyListingsRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/post-story': typeof PostStoryRoute
  '/reels': typeof ReelsRoute
  '/unified-inbox': typeof UnifiedInboxRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/messages': typeof MessagesRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/my-listings': typeof MyListingsRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/post-story': typeof PostStoryRoute
  '/reels': typeof ReelsRoute
  '/unified-inbox': typeof UnifiedInboxRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/messages'
    | '/my-appointments'
    | '/my-listings'
    | '/plans'
    | '/post'
    | '/post-reel'
    | '/post-story'
    | '/reels'
    | '/unified-inbox'
    | '/edit-listing/$id'
    | '/seller/$id'
    | '/vehicle/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/messages'
    | '/my-appointments'
    | '/my-listings'
    | '/plans'
    | '/post'
    | '/post-reel'
    | '/post-story'
    | '/reels'
    | '/unified-inbox'
    | '/edit-listing/$id'
    | '/seller/$id'
    | '/vehicle/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/messages'
    | '/my-appointments'
    | '/my-listings'
    | '/plans'
    | '/post'
    | '/post-reel'
    | '/post-story'
    | '/reels'
    | '/unified-inbox'
    | '/edit-listing/$id'
    | '/seller/$id'
    | '/vehicle/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CheckoutRoute: typeof CheckoutRoute
  MessagesRoute: typeof MessagesRoute
  MyAppointmentsRoute: typeof MyAppointmentsRoute
  MyListingsRoute: typeof MyListingsRoute
  PlansRoute: typeof PlansRoute
  PostRoute: typeof PostRoute
  PostReelRoute: typeof PostReelRoute
  PostStoryRoute: typeof PostStoryRoute
  ReelsRoute: typeof ReelsRoute
  UnifiedInboxRoute: typeof UnifiedInboxRoute
  EditListingIdRoute: typeof EditListingIdRoute
  SellerIdRoute: typeof SellerIdRoute
  VehicleIdRoute: typeof VehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-appointments': {
      id: '/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof MyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-reel': {
      id: '/post-reel'
      path: '/post-reel'
      fullPath: '/post-reel'
      preLoaderRoute: typeof PostReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-story': {
      id: '/post-story'
      path: '/post-story'
      fullPath: '/post-story'
      preLoaderRoute: typeof PostStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unified-inbox': {
      id: '/unified-inbox'
      path: '/unified-inbox'
      fullPath: '/unified-inbox'
      preLoaderRoute: typeof UnifiedInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-listing/$id': {
      id: '/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof EditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CheckoutRoute: CheckoutRoute,
  MessagesRoute: MessagesRoute,
  MyAppointmentsRoute: MyAppointmentsRoute,
  MyListingsRoute: MyListingsRoute,
  PlansRoute: PlansRoute,
  PostRoute: PostRoute,
  PostReelRoute: PostReelRoute,
  PostStoryRoute: PostStoryRoute,
  ReelsRoute: ReelsRoute,
  UnifiedInboxRoute: UnifiedInboxRoute,
  EditListingIdRoute: EditListingIdRoute,
  SellerIdRoute: SellerIdRoute,
  VehicleIdRoute: VehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
