/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as PostReelRouteImport } from './routes/post-reel'
import { Route as PostRouteImport } from './routes/post'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as EditListingIdRouteImport } from './routes/edit-listing.$id'

const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const PostReelRoute = PostReelRouteImport.update({
  id: '/post-reel',
  path: '/post-reel',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditListingIdRoute = EditListingIdRouteImport.update({
  id: '/edit-listing/$id',
  path: '/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/my-listings': typeof MyListingsRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/reels': typeof ReelsRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/my-listings': typeof MyListingsRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/reels': typeof ReelsRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/my-listings': typeof MyListingsRoute
  '/post': typeof PostRoute
  '/post-reel': typeof PostReelRoute
  '/reels': typeof ReelsRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/my-listings'
    | '/post'
    | '/post-reel'
    | '/reels'
    | '/edit-listing/$id'
    | '/vehicle/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/my-listings'
    | '/post'
    | '/post-reel'
    | '/reels'
    | '/edit-listing/$id'
    | '/vehicle/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/my-listings'
    | '/post'
    | '/post-reel'
    | '/reels'
    | '/edit-listing/$id'
    | '/vehicle/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CheckoutRoute: typeof CheckoutRoute
  MyListingsRoute: typeof MyListingsRoute
  PostRoute: typeof PostRoute
  PostReelRoute: typeof PostReelRoute
  ReelsRoute: typeof ReelsRoute
  EditListingIdRoute: typeof EditListingIdRoute
  VehicleIdRoute: typeof VehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-reel': {
      id: '/post-reel'
      path: '/post-reel'
      fullPath: '/post-reel'
      preLoaderRoute: typeof PostReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-listing/$id': {
      id: '/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof EditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CheckoutRoute: CheckoutRoute,
  MyListingsRoute: MyListingsRoute,
  PostRoute: PostRoute,
  PostReelRoute: PostReelRoute,
  ReelsRoute: ReelsRoute,
  EditListingIdRoute: EditListingIdRoute,
  VehicleIdRoute: VehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
